name: Create Pull Request

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '!.github/workflows/**'

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Delete test.txt
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b del_test
          git rm test.txt
          git commit -m "[del_test] Remove test.txt"
          git push origin del_test
      - name: Create Pull Request
        run: gh pr create --base master --head del_test --title "[del_test] Remove test.txt" --body "Remove test.txt"
        env:
          GH_TOKEN: ${{ secrets.FINE_GRAINED_PERSONAL_ACCESS_TOKEN }}
